---

- hosts: GNS3-n9kv-spines
  vars:
    nxos_provider:
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: nxapi
      use_ssl: True 
      validate_certs: False
      host: "{{ inventory_hostname }}"

  tasks:
    - name: WIPE DEMO
      nxos_feature:
        feature: "{{item.feature }}"
        provider: "{{ nxos_provider }}"
        state: disabled
      with_items:
        - { feature: bgp }
        - { feature: ospf }
        #- { feature: "nv overlay" }

    - name: WIPE NV OVERLAY EVPN CONFIG
      nxos_evpn_global:
        nv_overlay_evpn: false
        provider: "{{ nxos_provider }}"

    - name: RESET ALL INTERFACES
      nxos_interface:
        interface: "{{item.name }}"
        mode: layer2
        provider: "{{ nxos_provider }}"
      with_items: "{{ interfaces }}"

    - name: REMOVE LOGICAL INTERFACES
      nxos_interface:
        interface_type: loopback
        state: absent
        provider: "{{ nxos_provider }}"

- hosts: GNS3-n9kv-leafs

  vars:
    nxos_provider:
      username: "{{ un }}"
      password: "{{ pwd }}"
      transport: nxapi
      use_ssl: True 
      validate_certs: False
      host: "{{ inventory_hostname }}"

  tasks:
    - name: WIPE DEMO
      nxos_feature:
        feature: "{{item.feature }}"
        provider: "{{ nxos_provider }}"
        state: disabled
      with_items:
        - { feature: bgp }
        - { feature: ospf }
        - { feature: interface-vlan}
        #- { feature: "nv overlay" }
        #- { feature: "vnseg_vlan"}

    - name: WIPE NV OVERLAY EVPN CONFIG
      nxos_evpn_global:
        nv_overlay_evpn: false
        provider: "{{ nxos_provider }}"

    - name: REMOVE NVE
      nxos_interface:
        interface: "nve1"
        state: absent
        provider: "{{ nxos_provider }}"


    - name: REMOVE VRF
      nxos_vrf:
        vrf: "{{ item }}"
        state: absent
        provider: "{{ nxos_provider }}"
      with_items:
      - 'tenant-1'
      - 'tenant-2'

    - name: REMOVE LOGICAL INTERFACES
      nxos_interface:
        interface_type: "{{ item }}"
        state: absent
        provider: "{{ nxos_provider }}"
      with_items:
      - svi
      - loopback

    - name: RESET ALL L3 INTERFACES
      nxos_interface:
        interface: "{{item.name }}"
        mode: layer2
        provider: "{{ nxos_provider }}"
      with_items: "{{ interfaces }}"

    - name: RESET ALL L2 INTERFACES
      nxos_interface:
        interface: "{{ item }}"
        state: default
        provider: "{{ nxos_provider }}"
      with_items:
      -  Ethernet1/5
      -  Ethernet1/6
      -  Ethernet1/7
      -  Ethernet1/8


    - name: REMOVE ANYCAST GATEWAY
      nxos_overlay_global:
        anycast_gateway_mac: default
        provider: "{{ nxos_provider }}"


    - name: REMOVE VLANS
      nxos_vlan:
        vlan_id: "{{ item }}"
        state: absent
        provider: "{{ nxos_provider }}"
      with_items:
      - 11
      - 12
      - 21
      - 22
      - 1001
      - 1002







#- hosts: all
  #tasks:
  #  - name: save config
  #    nxos_save_config: host={{ inventory_hostname }}
