---
#Leaf variables

  nxos_provider:
    username: "{{ un }}"
    password: "{{ pwd }}"
    transport: nxapi
    use_ssl: True 
    validate_certs: False
    host: "{{ inventory_hostname }}"

  nve: nve1

  features:
  - { feature: bgp }
  - { feature: ospf }
  - { feature: interface-vlan }
  - { feature: "nv overlay" }
  - { feature: vnseg_vlan }


  asn: '65001'

  address_families:
  - { afi: ipv4, safi: unicast }
  - { afi: l2vpn, safi: evpn }


  bgp_neighbors:
  - { remote_as: '65001', neighbor: 1.1.1.1, update_source: Loopback0 }
  - { remote_as: '65001', neighbor: 2.2.2.2, update_source: Loopback0 }

  default_vrf_interfaces:
  - { interface: Ethernet1/1 }
  - { interface: Ethernet1/2 }
  - { interface: Loopback0 }
