---

  nxos_provider:
    username: "{{ un }}"
    password: "{{ pwd }}"
    transport: nxapi
    use_ssl: True 
    validate_certs: False
    host: "{{ inventory_hostname }}"


  vrf: tenant-1

  vlan_id: '1001'
  vni: '10001'

  nve: nve1

  svi: Vlan1001

  vlans:
  - { vlan_id: '11', vni: '10011' }

  vlan_ip:
  - { name: Vlan11, ipv4: 11.11.11.1/24 }

  switchports:
  - { name: Eth1/5, vlan: '11' }
  - { name: Eth1/6, vlan: '11' }

  asn: '65001'

  address_families:
  - { afi: ipv4, safi: unicast }
